#!/bin/bash
set -e

sudo apt install -y apt-transport-https ca-certificates

sudo apt-key adv \
  --keyserver hkp://p80.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

sudo bash -c 'echo deb https://apt.dockerproject.org/repo ubuntu-xenial main > /etc/apt/sources.list.d/docker.list'

sudo apt update
sudo apt install -y docker-engine

sudo gpasswd -a zero docker
